### ISSUE TITLE
Update to jquery mobile 1.3.0

### ISSUE THREAD

**Issue by marceloverdijk** [ionic-team/graphite#1]
Placeholder issue to track jquery 1.3.0 compatibility.

**Comment by urbien** [comment]
+1
would love to try graphite, but we are already using jqm 1.3

**Comment by mlynch** [comment]
This will definitely be happening, and we've got a lot more we want to do with this project, so +1 as well :)

**Comment by marceloverdijk** [comment]
@mlynch is there any information (blog?) available you guys want to do with this project?

**Comment by mlynch** [comment]
No info or blog yet. The goal was basically to create some really awesome themes for jQuery Mobile, and contribute design work back to the project. Beyond that, we want to give a new "default" look for jQM because things get stale and the original jQM themes need a lift.

What excites you about graphite? I would love your feedback!

**Comment by urbien** [comment]
Max, yes, JQM themes are so stale. JQM developers need a large variety of themes to choose from. The gallery of themes could include free, like graphite, and purchasable, may be even for a small price of $1-$5, and $100-$300 if exclusive, which is then taken out of the gallery after the purchase. There also could be custom design ordering, for a higher price. We are thinking of setting up such a marketplace on http://urbien.com and integrating it with our app builder, so that with one-two taps developers could replace the theme and see how it looks with their app. We already have amazon.com and paypal.com connected for payments, have ordering system, have tickets system for the support line, etc.

Other elements that could be part of the theme package, are splash screen, logo, background images, special images for headers and other elements (which you probably understand better than I), icon font (font awesome and alternatives), etc. - things which would make JQM apps look unique and visually appealing. Unfortunately now even with the themeing they look so run-of-the-mill, unless a custom designer work is applied, like things done by the guys I met yesterday at the Techcrunch meetup http://www.hellogriswold.com.
Does this all make sense?

**Comment by marceloverdijk** [comment]
@mlynch I was mainly trigger by the sleek themes. They really look good as I agree the default themes (and using themeroller doesn't really change that) are indeed look old-fashioned...
When do you think you will be supporting jqm 1.3?

@urbien A marketplace for jqm themes would indeed be nice.

**Comment by gligorov** [comment]
Great themes, and would love to use them, but we are on 1.3 and can't use them.  Any update on when 1.3 compatible version may be coming now that the Final release of JQM 1.3 is available?

**Comment by bistory** [comment]
Is there any news about supporting jqm 1.3 ?

**Comment by marlonbernardes** [comment]
+1

**Comment by drb** [comment]
Would love to see some Graphite hotness on 1.3.x!

**Comment by mlynch** [comment]
Moving to 1.3.1 hopefully today! Also changing the script so it's easier to upgrade between versions.

**Comment by mlynch** [comment]
Okay, Graphite is now 1.3.1 enabled. There are a few small design things we will be tweaking, but this one is ready to go!

Thanks so much!

**Comment by KevinTCoughlin** [comment]
Awesome! Thank you for updating the project!

**Comment by bistory** [comment]
Thank you very much !
