### ISSUE TITLE
IE9 navbar items are black not white

### ISSUE THREAD

**Issue by nathanwaters** [ionic-team/graphite#6]
Screenshot:

![ie9](https://f.cloud.github.com/assets/1635052/435402/6ad65b22-afd0-11e2-9932-58b3e747e51b.JPG)

**Comment by mlynch** [comment]
Haha, what? Crazy IE.

I'll take a look!

**Comment by KevinTCoughlin** [comment]
I believe this issue is due to the use of linear gradients to set button colors in the Graphite theme as IE9 [does not support](https://developer.mozilla.org/en-US/docs/CSS/linear-gradient#Browser_compatibility) them (IE10+ does). 

If you generate the appropriate background style for the classes effected (btn up, btn down, hover) then it seems to be fixed. Currently, graphite generates the background styles using jQM default colors hence the dark grey. At least that's the solution I used in my fork.
